# Generated by Django 4.0.2 on 2024-10-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_fund',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='withdrawn_fund',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
