# Generated by Django 4.0.2 on 2024-06-17 21:21

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Shoes', 'SHOES'), ('Athletic Shoes', 'Athletic Shoes'), ('Casual Shoes', 'Casual Shoes'), ('Formal Shoes', 'Formal Shoes'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Flip-Flops', 'Flip-Flops'), ('Loafers', 'Loafers'), ('Slip-Ons', 'Slip-Ons'), ('Sneakers', 'Sneakers'), ('Brogues', 'Brogues'), ('Running Shoes', 'Running Shoes'), ('Ballet Flats', 'Ballet Flats'), ('bags', 'BAGS')], default='category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
