# Generated by Django 4.0.2 on 2024-06-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_category_product_created_at_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
