# Generated by Django 4.0.2 on 2024-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_trashrequest_trash_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashrequest',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
