# Generated by Django 4.0.2 on 2024-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_alter_trashrequest_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashrequest',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
