# Generated by Django 4.0.2 on 2024-10-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recycling', '0004_alter_trashrequest_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashrequest',
            name='total_fund',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='trashrequest',
            name='withdrawn_fund',
            field=models.IntegerField(default=0.0),
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_type', multiselectfield.db.fields.MultiSelectField(choices=[('Health', 'Health Care Need'), ('School', 'Educational Need'), ('EcoFashion', 'Eco Fashion'), ('EcoFashion', 'Eco Fashion'), ('MTN Airtime', 'MTN Airtime'), ('GLO Airtime', 'GLO Airtime'), ('AirTel Airtime', 'AirTel Airtime'), ('9Mobile Airtime', '9Mobile Airtime'), ('MTN Data', 'MTN Data'), ('GLO Data', 'GLO Data'), ('AirTel Data', 'AirTel Data'), ('9Mobile Data', '9Mobile Data')], default='', max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('disbursed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
