# Generated by Django 4.0.2 on 2024-10-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0004_trashrequest_dropoff_trashrequest_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashrequest',
            old_name='points',
            new_name='earned',
        ),
    ]
