# Generated by Django 4.0.2 on 2024-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0005_trashrequest_total_fund_trashrequest_withdrawn_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='withdraw_type',
            field=models.CharField(choices=[('Health', 'Health Care Need'), ('School', 'Educational Need'), ('EcoFashion', 'Eco Fashion'), ('EcoFashion', 'Eco Fashion'), ('MTN Airtime', 'MTN Airtime'), ('GLO Airtime', 'GLO Airtime'), ('AirTel Airtime', 'AirTel Airtime'), ('9Mobile Airtime', '9Mobile Airtime'), ('MTN Data', 'MTN Data'), ('GLO Data', 'GLO Data'), ('AirTel Data', 'AirTel Data'), ('9Mobile Data', '9Mobile Data')], default='', max_length=100),
        ),
    ]
