# Generated by Django 4.0.2 on 2024-10-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0006_alter_fundrequest_withdraw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
