# Generated by Django 4.0.2 on 2024-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0007_fundrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashrequest',
            name='DropOff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trashrequest',
            name='Phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trashrequest',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trashrequest',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
    ]
