# Generated by Django 4.0.2 on 2024-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0008_trashrequest_dropoff_trashrequest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashrequest',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
