# Generated by Django 4.0.2 on 2024-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0010_alter_fundrequest_health_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='airtime_choice',
            field=models.CharField(blank=True, choices=[('Airtime Network', 'Airtime Network'), ('MTN Airtime', 'MTN Airtime'), ('GLO Airtime', 'GLO Airtime'), ('AirTel Airtime', 'AirTel Airtime'), ('9Mobile Airtime', '9Mobile Airtime')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='data_choice',
            field=models.CharField(blank=True, choices=[('Data Network', 'Data Network'), ('MTN Data', 'MTN Data'), ('GLO Data', 'GLO Data'), ('AirTel Data', 'AirTel Data'), ('9Mobile Data', '9Mobile Data')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='health_choice',
            field=models.CharField(blank=True, choices=[('Choose purpose', 'Choose purpose'), ('Medication', 'Medication'), ('Medical test', 'Medical test'), ('Hospital bill', 'Hospital bill'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='school_choice',
            field=models.CharField(blank=True, choices=[('School Purpose', 'School Purpose'), ('School fee', 'School fee'), ('feeding', 'feeding'), ('Book / Course materials', 'Book / Course materials'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='withdraw_type',
            field=models.CharField(choices=[('Withdraw purpose', 'Withdraw purpose'), ('Health', 'Health Care Need'), ('School', 'Educational Need'), ('EcoFashion', 'Eco Fashion'), ('Airtime', 'Airtime'), ('Data', 'Data'), ('others', 'Others')], max_length=100),
        ),
    ]
