# Generated by Django 5.1.1 on 2025-05-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0012_alter_fundrequest_airtime_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='health_choice',
            field=models.CharField(blank=True, choices=[('Choose purpose', 'Choose purpose'), ('Medication', 'Medication'), ('Medical test', 'Medical test'), ('Hospital bill', 'Hospital bill'), ('others', 'Others')], default='Choose purpose', max_length=100, null=True),
        ),
    ]
